server:
  port: 8080

spring:
  application:
    name: chat-system
  
  # MongoDB 설정
  data:
    mongodb:
      uri: mongodb://localhost:27017/chatdb
      repositories:
        enabled: true
  
  # Redis 설정
  redis:
    host: localhost
    port: 6379
    timeout: 3000ms
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        min-idle: 0
        max-wait: -1ms

# Socket.io 설정
socketio:
  host: localhost
  port: 9092
  boss-threads: 4
  worker-threads: 100
  allow-custom-requests: true
  upgrade-timeout: 1000
  ping-timeout: 5000
  ping-interval: 25000

# 채팅 시스템 설정  
chat:
  max-message-length: 1000
  rate-limit:
    messages-per-minute: 60
  rooms:
    max-users-per-room: 1000
    max-rooms-per-user: 10

# 모니터링 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    kr.co.chat: DEBUG
    com.corundumstudio.socketio: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 